% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  man]{apa7}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{english}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% Table formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\centering\begin{threeparttable}}
%   {\end{threeparttable}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\centering\begin{ThreePartTable}}{\end{ThreePartTable}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% Overwrite redefinition of paragraph and subparagraph by the default LaTeX template
% See https://github.com/crsh/papaja/issues/292
\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries\itshape\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-\z@\relax}%
  {\normalfont\normalsize\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother

\makeatletter
\usepackage{etoolbox}
\patchcmd{\maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\patchcmd{\maketitle}
  {\section{\protect\normalfont{\@title}}}
  {\section*{\protect\normalfont{\@title}}}
  {}{\typeout{Failed to patch title.}}
\makeatother

\usepackage{xpatch}
\makeatletter
\xapptocmd\appendix
  {\xapptocmd\section
    {\addcontentsline{toc}{section}{\appendixname\ifoneappendix\else~\theappendix\fi\\: #1}}
    {}{\InnerPatchFailed}%
  }
{}{\PatchFailed}
\keywords{labor migration, left-behind children, educational performance\newline\indent Word count: 6,000}
\DeclareDelayedFloatFlavor{ThreePartTable}{table}
\DeclareDelayedFloatFlavor{lltable}{table}
\DeclareDelayedFloatFlavor*{longtable}{table}
\makeatletter
\renewcommand{\efloat@iwrite}[1]{\immediate\expandafter\protected@write\csname efloat@post#1\endcsname{}}
\makeatother
\usepackage{lineno}

\linenumbers
\usepackage{csquotes}
\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-\z@\relax}%
  {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother

\usepackage{float}
\usepackage{booktabs}
\usepackage{siunitx}
\usepackage{setspace}
\onehalfspacing

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Newly Left-Behind Children's Educational Performance Drops Slightly After Parental Migration},
  pdfauthor={Jiancheng Gu1},
  pdflang={en-EN},
  pdfkeywords={labor migration, left-behind children, educational performance},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Newly Left-Behind Children's Educational Performance Drops Slightly After Parental Migration}
\author{Jiancheng Gu\textsuperscript{1}}
\date{}


\shorttitle{Left-Behind Children}

\authornote{

This paper's open science repository: \url{https://github.com/jchgu/MScThesis}

Correspondence concerning this article should be addressed to Jiancheng Gu, Dr.-Karl-Dorrek-Strasse 30, 3500 Krems, Austria. E-mail: \href{mailto:jiancheng.gu@donau-uni.ac.at}{\nolinkurl{jiancheng.gu@donau-uni.ac.at}}

}

\affiliation{\vspace{0.5cm}\textsuperscript{1} Department for Migration and Globalisation, Universität für Weiterbildung Krems}

\note{

November 09, 2023

}

\abstract{%
Millions of children worldwide are ``left behind'' at home communities as their parents migrate away for work.
Parents' labor migration increases household income but decreases parental care, thereby exerting mixed influences on child development outcomes like educational attainment.
To what extent do different arrangements of parental migration affect children's educational performance in the short term?
Studying the case of China, I obtained a sample of four thousand junior high school students from a nationally representative two-wave panel survey.
I differentiated household migration arrangements of any one parent, of mother only, of father only, and of both parents.
I measured children's schooling performance by cognitive test scores and academic exam grades.
For causal inference, I built difference-in-differences models with propensity score matching.
Results show that the newly left-behind children's performance at school dropped slightly compared to that of non-left-behind peers.
Father-only migration is negatively associated with children's cognitive abilities.
Mother-only migration is negatively associated with children's academic grades and cognitive abilities.
}



\begin{document}
\maketitle

\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

Globally, millions of children reside in their home communities but live apart from their parents as either one or both parents have migrated for work. These are the so-called ``left-behind children'' or ``stay-behind children.'' They are common in migrant-sending regions, such as Latin America, Sub-Sahara Africa, East Europe, and large parts of Asia. Researchers estimated that one-sixth of Mexican children (DeWaard et al., 2018), one-fifth of Bulgarian children (ROMACT, 2021), and one-fourth of Chinese children were separated from their migrating parents (NBS et al., 2017). The issue of left-behind children has caught the attention of policymakers and legislators. In a resolution, the Parliamentary Assembly of the Council of Europe expressed concern about ``the scale of this phenomenon and the long-term damage it creates'' and declared that leaving ``millions of labour migrants' children without parental care is a mass violation of human rights'' (PACE, 2021).

How are stay-behind children faring in the absence of parents? Research findings are mixed due to the differential effects of parental migration. Consider children's education. According to Venta and Cuervo (2022) and Van Hook and Glick (2020), labor migrants send remittances back, which can fund children's schooling as well as improve their nutritional and living conditions. To what degree can the inflow of remittances compensate for the loss of parental attention? Parental migration decreases the amount and quality of parental guidance, protection, and support. It is uncertain how these two opposing effects together shape children's educational performance. This uncertainty merits empirical investigation.

Quantitative social scientists have researched extensively about the education of left-behind children, but recent literature still has shortcomings. Some studies fail to capture the dynamic nature of migratory process as they draw upon cross-sectional data that focus on single time points (e.g. Ahmed et al., 2023; Gong \& Rao, 2023; Viet Nguyen \& Hoang Vu, 2023). Some other studies only probe correlation using regression analysis (e.g. L. Chen et al., 2023; Huang et al., 2020; R. Liu \& Hannum, 2023). These studies could have employed causal inference techniques.

My research question is: To what extent do different arrangements of parental migration affect the educational performance of left-behind children in the short term? I choose China as the case and analyze data from a two-wave panel survey. The nationally representative sample includes children in both urban and rural areas. I develop a difference-in-differences model for causal inference and apply propensity score matching for robustness checks. The outcome is measured with children's cognitive test score and academic exam grade. I demonstrate that parental migration reduces the educational performance of children staying behind, but only to a small extent.

\hypertarget{chinas-context}{%
\subsubsection{China's Context}\label{chinas-context}}

Three features make China a suitable case for studying left-behind children. The most prominent feature is the huge scale of internal labor migration. According to the National Bureau of Statistics, the year 2021 recorded 292.5 million in-country migrant workers. They form the backbone of essential industries, such as retail, transportation, and manufacturing. The 2015 one-percent National Population Sample Survey estimated that 68.7 million Chinese children were left behind (NBS et al., 2017; NBS, 2022).

The internal migration stemmed from the neoliberal economic regime. Scholars like Duckett (2020) and Zhang (2018) argued that China conforms to the neoliberal trend, extending the logic of the market to other domains of human life. In the 1980s, the ruling communist party ditched the planned economy, initiated market reforms, and opened up the country. Since then, China has integrated in the global economy and recorded substantial growth. The economic reform and globalization have enriched the coastal cities like Shanghai and Shenzhen. The rural hinterlands, however, have lagged behind. Simultaneously, many people have left the countryside for the city. The regional inequality needs social policy to amend. But China's welfare program, as Qian (2021) argued, is fragmented and stratified. People who reap the greatest benefits are public servants, urban dwellers, and formally employed workers. As rural migrants arrive in the city, they find themselves with limited access to social welfare, such as health care and children's education (Qian, 2021). The welfare system's exclusion of rural migrants means that the state shifts its responsibility to individuals, resembling the neoliberal governmentality (Zhan, 2020).

The institutional discrimination against labor migrants finds its roots in China's ``multilevel citizenship'' system. As Vortherms (2023) explained, the constituents of citizenship -- ``membership rules'' and ``rights entitlements'' -- operate below the national level in China. The local state confers most of the rights and defines who is eligible to these rights through \emph{hukou}, or the household registration system. The system differentiates people into local versus external and urban versus rural. In the rural-urban divide, urban hukou holders enjoy greater access to higher-quality welfare benefits and public services compared to rural hukou holders. In the local-external divide, local hukou holders are those registered in the same county where they live. In theory, Chinese citizens can migrate freely within the country. In practice, they cannot change hukou freely. When rural residents move to the city, it takes months -- if not years -- to apply for a new hukou. Before receiving urban hukou, they can hardly send their children into public schools in the host city (Y. Chen \& Fu, 2023; Zhang, 2018). These institutions turn rural migrants into second-class citizens in effect. Migrant workers have organized petitions, strikes, and protests. These actions often fell on deaf ears and sometimes even ended with police crackdown (Chan, 2019; Göbel, 2021). Facing financial and policy constraints, many migrant laborers have to leave children in their hometowns. Only during the winter and summer breaks can these children reunite with parents.

How does China counter the issue of labor migration and left-behind children? According to Dong and Goodburn (2020), the government has gradually liberalized the multilevel citizenship scheme. It has introduced residence permit for internal migrants as the basis for social entitlements. First-tier cities like Beijing and Shanghai have brought forth a point-based system to grant hukou to newcomers. The system's evaluation criteria include in-demand talents and skills, educational and professional qualifications, and consecutive years of employment and tax-payment. This parallels how European states differentially incorporate foreign immigrants into national welfare regimes (Pasquali, 2022). Another policy response, as stated by Roberts and Hannum (2018), is the centralized boarding school. The Ministry of Education promotes boarding schools in the rural county-seats. These schools serve as a cost-effective way to enroll students in surrounding villages and to look after the left-behind children. In reality, such schools ``are often ill-equipped to ensure the healthy upbringing and psychological wellbeing of children'' (p.~6).

\hypertarget{theory-and-hypotheses}{%
\subsubsection{Theory and Hypotheses}\label{theory-and-hypotheses}}

Between parental migration and children's education, the mechanisms trace to two theoretical frameworks. One is the resource generation model. It holds that parental migration brings forth greater resources that can help children acquire human capital -- the stock of ``knowledge, skills, and health that people accumulate over their lives'' (World Bank, 2020, p. 1). Yang (2008) noted that in the Philippines, a sharp depreciation of peso increased the amount of remittances from migrants working abroad. This subsequently boosted children's school enrollment and educational spending. Vikram (2021) performed propensity score matching and fixed-effect regression on a two-wave panel dataset featuring Indian children aged eight to eleven. She showed that fathers' migration was linked with increases in left-behind children's reading capability and educational expenditure (p.~991). In China, Gu (2022) interviewed migrant workers and their family members. She found that they aspire to move up the social ladder; Such aspiration translates into ``intensive and all-out investment in children's education'' (p.~526). Oftentimes, labor migration presented the only way to sustain their children's education and livelihood. Peng (2018) interviewed first-generation migrant mothers whose initial migration dated back to the 1990s. To them, ``good mothering'' primarily meant offering economic support for their children in education, which can help their children climb the ladder of success.

The other theoretical model is the family disruption model (Shen et al., 2021). Children flourish under parental nurturing care. This term refers to the ``stable environments that promote health and adequate nutrition, protect from threats \ldots{} opportunities for learning,'' and ``responsive, emotionally supportive and developmentally enriching relationships'' (Black et al., 2021, p. 1). According to C. Chen (2023), caregiver-child interactions are infrequent and unstable for left-behind children. The loss in such interactions ``mediates almost all of the adverse effects of parental absence.'' This conclusion was based on structural equation modeling using a cross-sectional survey with a sample of Chinese children aged three to fifteen. Murphy (2022) talked to children left behind in a Chinese village. Some of them ``embraced the `left-behind' label'' because it captured their need for more parental care (p.~185), ``especially companionship and affection in daily life'' (p.~186). In Romania, Udrea and Guiu (2022) and Diaconu-Gherasim et al. (2023) interviewed left-behind adolescents. Many of them felt disorientated about the lack of parents' support and oversight in schoolwork.

Given the two opposing effects, researchers have obtained mixed results on how parental migration impacts children's education. Botezat and Pfeiffer (2020) adopted past immigration rate as an instrumental variable. They found a positive effect of parents' migration on academic grades of adolescents aged eleven to fifteen in Romania. L. Wang et al. (2019) collected data from junior high school students in central China. Their two-way fixed-effect model showed no significant effect of parental migration on left-behind children's achievement in mathematical test. Chae and Glick (2019) analyzed the Migration and Remittances Household Survey of Kenya, Senegal, and Burkina Faso. They observed significant correlation between parental migration and left-behind children's school enrollment in Kenya, but not in the other two West African countries. Nguyen (2016) conducted fixed-effect regression and demonstrated that parental migration was associated with lower cognitive capabilities among Indian and Vietnamese children aged five to eight.

Parental migration immediately disrupts family structure, which in turn lowers academic performance of children. It takes longer time for labor migration to generate resources that improve children's educational attainment. I propose the first hypothesis:

\(H_1\) In the short term, parental migration reduces the educational performance of children left-behind.

\(H_1a\) In the short term, parental migration negatively affects left-behind children's cognitive test score.

\(H_1b\) In the short term, parental migration negatively affects left-behind children's academic exam score.

Researchers have studied whether the impact differs between mother's migration and father's migration. R. Liu and Hannum (2023) analyzed how fifteen-year-old students' academic performance is associated with parental absence across 59 countries, using the 2012 Program of International Student Assessment data. Compared to students living with both parents, students perform worse in academic tests when only mother is absent or both parents are absent; When only father is absent, however, students are not significantly below par. Xu et al. (2019) adopted a fixed-effects propensity score weighting model on cross-sectional data collected from seventh and ninth graders in rural areas across China. They found that the absence of father only or both parents had ``little or no association with negative outcomes'' on children's academic and cognitive performances. Only-mother absence, however, showed a ``strong association with negative outcomes'' (p.~1646). Chen et al. (2019) conducted structural equation modeling on the cross-sectional data collected from fourth to seventh graders in the countryside of one province. They found that maternal migration was ``negatively associated with children's social competence and academic performance,'' while paternal migration had no direct effects on the two outcomes (pp.~860-861).

Murphy (2020) and Fan (2023) noted that in some Asian and Latin American societies, the social norms designate men as breadwinners and women as caregivers. Under such norms, fathers' migration is more likely to win children's acceptance than does mothers' migration. Left-behind children may even resent their migrant mothers for transgressing on the expected care-giving roles. I propose the second hypothesis:

\(H_2\) In the short term, mother's migration more negatively affect the educational performance of children left-behind than do father's migration.

\(H_2a\) In the short term, mother's migration more negatively affect left-behind children's cognitive test score than do father's migration.

\(H_2b\) In the short term, mother's migration more negatively affect left-behind children's academic exam score than do father's migration.

\hypertarget{methods}{%
\subsection{Methods}\label{methods}}

\hypertarget{sampling}{%
\subsubsection{Sampling}\label{sampling}}

I obtained the data from the China Education Panel Survey (CEPS) (NSRC, n.d.). It is a nationally representative, school-based survey featuring junior high school students. Currently, two waves of data are available. The CEPS team operates under the National Survey Research Center at the Renmin University of China. The survey team adopted multi-stage stratified probability proportional to size sampling and administered a paper-and-pencil questionnaire to each participant. The wave one baseline survey took place in the 2013-2014 academic year with a sample size of about twenty thousand students in the seventh and ninth grades. They were nested in 438 classrooms of 112 schools in 28 urban districts or rural counties (hereafter `counties'). The wave two follow-up survey in the 2014-2015 academic year lost track of the ninth grade cohort and only surveyed 10279 of the seventh grade cohort. I further restricted the sample to students living with both parents at the original domicile (place of hukou registry) at the baseline survey. To tackle missing values, I adopted list-wise deletion for the dependent, independent, and control variables. The final sample size amounts to 4204.

\hypertarget{measurement}{%
\subsubsection{Measurement}\label{measurement}}

I explored two categories of educational performance: cognitive and academic abilities. One key dependent variable, the student's cognitive skill, was measured by a fifteen-minute standardized test administered by the CEPS research team. The test covered three types of reasoning: verbal, visuospatial, and numerical. The baseline and follow-up tests consisted of 20 and 35 items, respectively. The raw score was calculated based on Three-Parameter Logistic model of Item Response Theory (W. Wang \& Li, 2015). I transformed the raw scores to the 100-point scale. I chose the raw score instead of the z-score, as z-standardization fails to document the change of mean between time points, which is also of interest (Moeller, 2015).

Another dependent variable concerned students' academic performance. This was measured by the average scores of mid-term exams in Chinese, mathematics, and English as provided by each school. Exam scores are reliable indicators of learning performance, and are comparable across schools for the same cohort of students. This is related to how junior high schools operate within the compulsory education system in China. According to OECD (2016), China's junior secondary education is a unified system that does not distinguish between academic and vocational tracks. At school, the subjects of Chinese, mathematics, and English are core subjects and others as supplementary subjects. Throughout junior high school, students study the core subjects in preparation for the senior high school entrance exam. Within each cohort in one particular school, teachers use the same syllabus and administer the same exams during a given assessment period. Across cities and regions, junior high schools adopt the educational content and assessment set by the Ministry of Education (OECD, 2016).

I transformed the exam grades through the following steps. I first aligned different grading scales (full mark of 100, 120, and 150 for one subject) with the 100-point scale. After the conversion, I checked for abnormal values lower than zero or higher than one hundred. 36 observations were outliers, accounting for less than one percent of the sample. I retained these observations in the sample and trimmed the subject exam scores. The trimming ensured that all values would be within the 0-100 range. In this way, I can limit the impact of outliers. Finally, I calculated the average score of these three subjects.

The key independent variable, the parental migration status, was identified by two items in the parent survey. In both the baseline and the follow-up surveys, parents specified the family members living in the same household at the time. I constructed four treatment dummy variables measuring migration arrangements: any parents migrated, only father migrated, only mother migrated, and both parents migrated. The latter three arrangements are mutually exclusive. The control group consisted of parents staying with their children throughout the two waves of survey. I then removed the observations that reported parental divorce or death. These type of parental absence are irrelevant to migration.

The lists of covariates are in Table 1 -- Table 5 in the Results section. At the children's level, I controlled for age, sex, self-rated health, ethnicity, hukou type, number of siblings, whether the child had attended preschool, and whether the child attends boarding school. Age, sex, and health are associated with educational performance (Gu \& Yeung, 2021). Regarding ethnicity and hukou status, Han Chinese and urban hukou holders outperform ethnic minorities and rural hukou holders at school (Hasmath, 2023; Huang et al., 2020; D. Xu et al., 2018). Attending preschool in early childhood and enrolling in boarding school in adolescence are predictors of educational performance (Guo et al., 2021; M. Liu \& Villa, 2020; Zheng et al., 2021). I also included the number of siblings as a covariate, considering the quantity-quality trade-off in multi-child family (Doepke, 2015). At the household level, I controlled for the levels of education of father and mother, whether the parent has a white collar job, whether the household has internet access, the perceived household financial conditions, and the number of extracurricular books at home. These variables measure family socioeconomic status, which is related to children's educational achievement (J. Liu et al., 2020; Young \& Hannum, 2018). Finally, I controlled for the level of education that the child aspires to achieve and the parental expectation on the child's level of education. Children's academic achievement, their educational aspiration, and their parents' expectations are interrelated (Chen et al., 2023; Xu \& Montgomery, 2021). All control variables were measured in the baseline survey.

\hypertarget{analytical-strategy}{%
\subsubsection{Analytical Strategy}\label{analytical-strategy}}

I built a two-way fixed-effect regression model in a difference-in-differences (DID) design, utilizing parental migration as the treatment (Bai et al., 2018). The treatment group consists of students left behind by migrating parents at a certain point of time between the two waves of survey, and the control group includes those who do not. I compared the treatment group's pre- and post-treatment outcomes in relation to the control group.

Below is my first version of DID model: \[\Delta score_{i,j} = \alpha + \beta \cdot migr_{i} + \gamma \cdot score_{i;1} + \lambda \cdot S_{j} + \varepsilon_{i,j}\] It is unrestricted because it does not restrict on the coefficient associated with the baseline scores. The model is unadjusted as it does not adjust for additional covariates. Theoretically, it is unnecessary to include covariates that vary over group but remain constant over time; They would cancel out in the two-way fixed-effect model (Huntington-Klein, 2022). For student \(i\) in school \(j\), \(\Delta score_{i,j}\) is the change in test score between the two waves of surveys, \(migr_{i}\) is the treatment dummy variable, \(score_{i,j;1}\) is the test score at baseline, and \(S_{j}\) is the school fixed-effect. School fixed-effect can account for differences due to time-invariant factors at the school and county levels, as students nested in one school are also in the same county. The standard errors are clustered at the school level. An alternative is to use a class fixed-effect to control for time-invariant factors at the classroom level and above. However, about one-sixth of the students were reassigned into new classes at the end of baseline academic year. As the reassignment of classroom will complicate the model, I ruled out the classroom fixed-effect.

In addition, I present the second version of DID model: \[\Delta score_{i,j} = \alpha + \beta \cdot migr_{i} + \gamma \cdot score_{i;1} + \lambda \cdot S_{j} + \theta \cdot X_{i} + \varepsilon_{i,j}\] where \(X_{i}\) is the vector of covariates capturing the characteristics of children, their parents, and their households. This model includes covariate adjustment with an assumption: Covariates from the baseline survey may be associated with a coefficient that does not equal equal one.

I adopted \texttt{R} (version 4.3.2) for all the analyses (R Core Team, 2022). This involved the following packages: \texttt{tidyverse} (version 2.0.0) and \texttt{haven} (version 2.5.3) for data cleaning (Wickham et al., 2019, 2023); \texttt{fixest} (version 0.11.1) for econometric modeling (Berge et al., 2023); \texttt{MatchIt} (version 4.5.5) and \texttt{cobalt} (version 4.5.1) for matching (Greifer, 2023; Ho et al., 2011, 2023); \texttt{modelsummary} (version 1.4.3), \texttt{vtable} (version 1.4.5), and \texttt{kableExtra} (version 1.3.4) for presenting the results (Arel-Bundock, 2022; Huntington-Klein, 2023; Zhu, 2021).

\hypertarget{results}{%
\subsection{Results}\label{results}}

\hypertarget{descriptive-statistics}{%
\subsubsection{Descriptive Statistics}\label{descriptive-statistics}}

Table 1 illustrates the independent variables, namely the migration status reported in the wave two survey. All 4204 children were living with parents in one household in baseline, but about sixteen percent saw at least one parent migrated between the two waves of survey. I call these students ``newly left-behind children'' and their households ``new migration households.'' In these new migration households, only-mother migration and only-father migration each accounted for two out of five cases. The remaining one-fifth were both-parents migration.

\renewcommand{\arraystretch}{0.8}

\begin{table}

\caption{\label{tab:tab-idpvar}Independent variables by parental migration}
\centering
\begin{tabular}[t]{lll}
\toprule
Variable & N & Percent\\
\midrule
Parental Migration &  & \\
... No & 3529 & 84\%\\
... Yes & 675 & 16\%\\
Parental Migration Type &  & \\
... Both Parents at Home & 3529 & 84\%\\
\addlinespace
... Both Parents Migrated & 142 & 3\%\\
... Only Father Migrated & 266 & 6\%\\
... Only Mother Migrated & 267 & 6\%\\
\bottomrule
\end{tabular}
\end{table}

The dependent variables are summarized by the control group versus the treatment group in Table 2 and Figure 1 -- Figure 2. Compared to non-left-behind peers, newly left-behind children scored lower in wave two's cognitive and academic tests; Their cognitive test score increased less and their academic exam score dropped more. T-tests show that for the baseline outcomes, the differences of the mean values between-group are probably due to chance. For the wave two outcomes and the between-wave changes, the differences of the mean value are statistically significant.

\begin{table}

\caption{\label{tab:tab-dpvar}Dependent variables by parental migration}
\centering
\begin{tabular}[t]{llllll}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{4}{c}{Parental Migration} \\
\cmidrule(l{3pt}r{3pt}){2-5}
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{No = 3529} & \multicolumn{2}{c}{Yes = 675} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5}
Variable & Mean & Sd & Mean & Sd & Test\\
\midrule
Cognitive test score difference & 11 & 20 & 9.7 & 21 & p=0.031*\\
\hspace{1em}Wave 1 score & 57 & 17 & 56 & 17 & p=0.174\\
\hspace{1em}Wave 2 score & 68 & 19 & 65 & 20 & p<0.001***\\
Academic exam score difference & -2.8 & 11 & -4 & 12 & p=0.01**\\
\hspace{1em}Wave 1 score & 71 & 16 & 70 & 17 & p=0.077\\
\addlinespace
\hspace{1em}Wave 2 score & 68 & 18 & 66 & 20 & p=0.002**\\
\bottomrule
\multicolumn{6}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{6}{l}{\rule{0pt}{1em}* p < 0.05, ** p < 0.01, *** p < 0.001}\\
\end{tabular}
\end{table}

Table 3 summarizes the bivariate analysis on the binary control variables. New migration households had lower internet access rate. Among the newly left-behind children, male sex, past grade retention, and boarding at school were more common compared to the non-left-behind peers. Chi-square tests show that these differences in variance are unlikely due to chance.

\begin{table}

\caption{\label{tab:tab-ctvar-dit}Dichotomous control variables by parental migration}
\centering
\begin{tabular}[t]{llllll}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{4}{c}{Parental Migration} \\
\cmidrule(l{3pt}r{3pt}){2-5}
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{No = 3529} & \multicolumn{2}{c}{Yes = 675} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5}
Variable & N & Percent & N & Percent & Test\\
\midrule
child.is.girl &  &  &  &  & X2=13.14***\\
... 0 & 1694 & 48\% & 376 & 56\% & \\
... 1 & 1835 & 52\% & 299 & 44\% & \\
child.has.rural.hukou &  &  &  &  & X2=1.676\\
... 0 & 1939 & 55\% & 352 & 52\% & \\
\addlinespace
... 1 & 1590 & 45\% & 323 & 48\% & \\
child.in.boarding.school &  &  &  &  & X2=4.185*\\
... 0 & 2545 & 72\% & 460 & 68\% & \\
... 1 & 984 & 28\% & 215 & 32\% & \\
child.is.ethnic.minority &  &  &  &  & X2=0.582\\
\addlinespace
... 0 & 3289 & 93\% & 623 & 92\% & \\
... 1 & 240 & 7\% & 52 & 8\% & \\
child.went.to.preschool &  &  &  &  & X2=1.254\\
... 0 & 538 & 15\% & 115 & 17\% & \\
... 1 & 2991 & 85\% & 560 & 83\% & \\
\addlinespace
parent.has.white.collar.job &  &  &  &  & X2=0.125\\
... 0 & 2531 & 72\% & 479 & 71\% & \\
... 1 & 998 & 28\% & 196 & 29\% & \\
home.has.internet &  &  &  &  & X2=15.73***\\
... 0 & 1087 & 31\% & 261 & 39\% & \\
\addlinespace
... 1 & 2442 & 69\% & 414 & 61\% & \\
\bottomrule
\multicolumn{6}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{6}{l}{\rule{0pt}{1em}0 = No, 1 = Yes; * p < 0.05, ** p < 0.01, *** p < 0.001}\\
\end{tabular}
\end{table}

Table 4 displays the bivariate analysis for categorical control variables, and Table 5 documents their measurement scales. While the majority of mothers and fathers had only finished high school or below, they held big expectations for children. Eight out of ten parents wished that their children complete university education. Scholars like Luo et al. (2013) and Ng and Wei (2020) explained this pattern with the Chinese social norms and cultural traditions. In ancient China, the Confucian teaching emphasized the cultivation of personhood through learning, diligence, and persistence. In real life, knowledge could translate into power and privilege. Ordinary people could study for the highly competitive \emph{keju} (civil service examination). As the world's ``earliest meritocratic institution,'' this national exam system recruited top performers into the imperial government and the elite class (T. Chen et al., 2020, p. 2030). Nowadays in China, the emperor and \emph{keju} are long gone, but the influences are long-lasting. Chinese parents hope that their children receive the best education to secure a decent career (Luo et al., 2013; Ng \& Wei, 2020).

\begin{table}

\caption{\label{tab:tab-ctvar-cnt}Categorical and continuous control variables by parental migration}
\centering
\begin{tabular}[t]{llllll}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{4}{c}{Parental Migration} \\
\cmidrule(l{3pt}r{3pt}){2-5}
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{No = 3529} & \multicolumn{2}{c}{Yes = 675} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5}
Variable & Mean & Sd & Mean & Sd & Test\\
\midrule
child.age & 13 & 0.61 & 13 & 0.73 & F=2.996\\
child.number.of.sibling & 0.58 & 0.74 & 0.66 & 0.84 & F=6.155*\\
child.health & 4.2 & 0.87 & 4.1 & 0.9 & F=1.105\\
child.education.aspiration & 3.9 & 1.2 & 3.9 & 1.3 & F=0.861\\
parent.education.level & 1.9 & 1.2 & 1.9 & 1.2 & F=0.18\\
\addlinespace
parent.expectation & 4.2 & 0.92 & 4.1 & 0.97 & F=2.394\\
home.extracurricular.book & 3.4 & 1.2 & 3.3 & 1.3 & F=4.042*\\
home.economic.resource & 2.9 & 0.55 & 2.8 & 0.57 & F=1.503\\
\bottomrule
\multicolumn{6}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{6}{l}{\rule{0pt}{1em}* p < 0.05, ** p < 0.01, *** p < 0.001}\\
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:tab-ctvar-msr}Measurement and distribution of categorical variables}
\centering
\begin{tabular}[t]{lll}
\toprule
Variable & N & Percent\\
\midrule
child.health &  & \\
... 1 = Very poor & 24 & 1\%\\
... 2 = Somewhat poor & 118 & 3\%\\
... 3 = Moderate & 829 & 20\%\\
... 4 = Good & 1424 & 34\%\\
\addlinespace
... 5 = Very good & 1809 & 43\%\\
child.education.aspiration &  & \\
... 0 = Does not matter & 87 & 2\%\\
... 1 = Junior high school & 58 & 1\%\\
... 2 = Senior high school & 436 & 10\%\\
\addlinespace
... 3 = Associate college & 639 & 15\%\\
... 4 = University & 1241 & 30\%\\
... 5 = Postgraduate & 1743 & 41\%\\
parent.education.level &  & \\
... 0 = Primary school and below & 254 & 6\%\\
\addlinespace
... 1 = Junior high school & 1631 & 39\%\\
... 2 = Senior high school & 1278 & 30\%\\
... 3 = Associate college & 397 & 9\%\\
... 4 = University & 564 & 13\%\\
... 5 = Postgraduate & 80 & 2\%\\
\addlinespace
parent.expectation &  & \\
... 0 = Does not matter & 2 & 0\%\\
... 1 = Junior high school & 36 & 1\%\\
... 2 = Senior high school & 275 & 7\%\\
... 3 = Associate college & 446 & 11\%\\
\addlinespace
... 4 = University & 1616 & 38\%\\
... 5 = Postgraduate & 1829 & 44\%\\
home.extracurricular.book &  & \\
... 1 = Very few & 401 & 10\%\\
... 2 = Not many & 426 & 10\%\\
\addlinespace
... 3 = Some & 1360 & 32\%\\
... 4 = Quite a few & 1135 & 27\%\\
... 5 = A great number & 882 & 21\%\\
home.economic.resource &  & \\
... 1 = Very poor & 111 & 3\%\\
\addlinespace
... 2 = Somewhat poor & 611 & 15\%\\
... 3 = Moderate & 3221 & 77\%\\
... 4 = Somewhat rich & 249 & 6\%\\
... 5 = Very rich & 12 & 0\%\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{regression-analysis}{%
\subsubsection{Regression Analysis}\label{regression-analysis}}

I first explain the results on children's cognitive test score. The unadjusted DID models show that newly left-behind adolescents are more likely to score lower in cognitive tests than do their non-left-behind counterparts (see Table 6). This lends support to Hypothesis 1a. Parental migration is linked to a 2.59 points decrease in cognitive test score. Hypothesis 2a is only partially supported. Compared with the non-left-behind peers, children with only father absent are associated with greater decrease (2.78 points) in cognitive test score than those with only mother absent (2.32 points). The adjusted DID models produce results similar to the unadjusted models, with one exception (see Table 7). That is, for the cognitive score, the both-parent-migrated coefficient's magnitude is lower than that of father-migrated.

\begin{table}

\caption{Parental migration’s effect on children’s cognitive test score}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-2.59}*** & \num{-2.32}* & \num{-2.78}** & \num{-2.81}*\\
 & (\num{0.63}) & (\num{1.01}) & (\num{1.00}) & (\num{1.26})\\
Baseline.score & \num{-0.71}*** & \num{-0.71}*** & \num{-0.71}*** & \num{-0.71}***\\
 & (\num{0.02}) & (\num{0.02}) & (\num{0.02}) & (\num{0.02})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.376} & \num{0.379} & \num{0.383} & \num{0.385}\\
R2 Adj. & \num{0.359} & \num{0.360} & \num{0.364} & \num{0.365}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}No control variables included in these models}\\
\end{tabular}
\end{table}

\begin{table}

\caption{Parental migration’s effect on children’s cognitive test score}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-2.41}*** & \num{-2.21}* & \num{-2.59}* & \num{-2.42}\\
 & (\num{0.63}) & (\num{0.99}) & (\num{1.04}) & (\num{1.30})\\
Baseline.score & \num{-0.78}*** & \num{-0.79}*** & \num{-0.78}*** & \num{-0.79}***\\
 & (\num{0.02}) & (\num{0.02}) & (\num{0.02}) & (\num{0.02})\\
child.age & \num{-3.43}*** & \num{-3.55}*** & \num{-3.58}*** & \num{-3.39}***\\
 & (\num{0.51}) & (\num{0.54}) & (\num{0.53}) & (\num{0.54})\\
child.is.girl & \num{-0.65} & \num{-0.39} & \num{-0.62} & \num{-0.56}\\
 & (\num{0.57}) & (\num{0.62}) & (\num{0.59}) & (\num{0.61})\\
child.health & \num{-0.15} & \num{-0.06} & \num{-0.25} & \num{-0.15}\\
 & (\num{0.32}) & (\num{0.32}) & (\num{0.35}) & (\num{0.34})\\
child.has.rural.hukou & \num{0.32} & \num{0.59} & \num{0.25} & \num{0.81}\\
 & (\num{0.65}) & (\num{0.66}) & (\num{0.68}) & (\num{0.70})\\
child.number.of.sibling & \num{-0.93}* & \num{-0.99}* & \num{-0.82}* & \num{-0.92}*\\
 & (\num{0.39}) & (\num{0.43}) & (\num{0.41}) & (\num{0.42})\\
child.went.to.preschool & \num{2.28}** & \num{2.08}* & \num{2.15}** & \num{1.99}*\\
 & (\num{0.77}) & (\num{0.83}) & (\num{0.80}) & (\num{0.82})\\
child.in.boarding.school & \num{1.10} & \num{1.09} & \num{1.11} & \num{0.72}\\
 & (\num{1.02}) & (\num{1.00}) & (\num{1.04}) & (\num{0.96})\\
child.education.aspiration & \num{1.76}*** & \num{1.71}*** & \num{1.73}*** & \num{1.81}***\\
 & (\num{0.27}) & (\num{0.29}) & (\num{0.27}) & (\num{0.29})\\
child.is.ethnic.minority & \num{1.47} & \num{1.57} & \num{1.08} & \num{1.22}\\
 & (\num{1.54}) & (\num{1.67}) & (\num{1.73}) & (\num{1.85})\\
parent.expectation & \num{2.42}*** & \num{2.53}*** & \num{2.46}*** & \num{2.39}***\\
 & (\num{0.34}) & (\num{0.35}) & (\num{0.33}) & (\num{0.34})\\
parent.has.white.collar.job & \num{-0.84} & \num{-0.88} & \num{-0.69} & \num{-0.77}\\
 & (\num{0.57}) & (\num{0.58}) & (\num{0.57}) & (\num{0.61})\\
parent.education.level & \num{0.56} & \num{0.69}* & \num{0.41} & \num{0.55}\\
 & (\num{0.31}) & (\num{0.32}) & (\num{0.34}) & (\num{0.34})\\
home.economic.resource & \num{-0.55} & \num{-0.65} & \num{-0.14} & \num{-0.21}\\
 & (\num{0.52}) & (\num{0.52}) & (\num{0.52}) & (\num{0.55})\\
home.extracurricular.book & \num{0.00} & \num{-0.06} & \num{-0.05} & \num{-0.01}\\
 & (\num{0.24}) & (\num{0.25}) & (\num{0.25}) & (\num{0.25})\\
home.has.internet & \num{-0.46} & \num{-0.72} & \num{-0.68} & \num{-0.96}\\
 & (\num{0.62}) & (\num{0.71}) & (\num{0.68}) & (\num{0.71})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.421} & \num{0.423} & \num{0.427} & \num{0.428}\\
R2 Adj. & \num{0.403} & \num{0.403} & \num{0.407} & \num{0.407}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\end{tabular}
\end{table}

Next, I set forth the results on children's academic test grades. In line with Hypothesis 1b, the unadjusted DID models show that newly left-behind adolescents tend to perform worse in school exams than their non-left-behind peers (see Table 8 below). Parental migration is associated with a drop of 1.13 points in academic exam score. Hypothesis 2b finds partial support. The exam grade of only-mother-migrated children sees a 2.06 points decrease relative to non-left-behind counterparts. In the scenarios of only father migrated and both parents migrated, the results are not statistically significant. The adjusted DID models' results largely resemble those from the unadjusted models (See Table 9 in the appendix). Adding control variables measured in the baseline survey does not change the coefficients for parental migration.

\begin{table}

\caption{Parental migration’s effect on children’s academic exam score}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-1.13}* & \num{-2.06}* & \num{-0.76} & \num{0.13}\\
 & (\num{0.50}) & (\num{0.88}) & (\num{0.65}) & (\num{0.65})\\
Baseline.score & \num{0.04} & \num{0.05} & \num{0.05} & \num{0.05}\\
 & (\num{0.03}) & (\num{0.03}) & (\num{0.03}) & (\num{0.03})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.469} & \num{0.485} & \num{0.473} & \num{0.488}\\
R2 Adj. & \num{0.455} & \num{0.469} & \num{0.457} & \num{0.472}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}No control variables included in these models}\\
\end{tabular}
\end{table}

\begin{table}

\caption{Parental migration’s effect on children’s academic exam score}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-1.07}* & \num{-2.05}* & \num{-0.66} & \num{0.22}\\
 & (\num{0.48}) & (\num{0.82}) & (\num{0.64}) & (\num{0.66})\\
Baseline.score & \num{-0.01} & \num{-0.01} & \num{-0.01} & \num{-0.01}\\
 & (\num{0.03}) & (\num{0.03}) & (\num{0.03}) & (\num{0.03})\\
child.age & \num{-0.74}*** & \num{-0.58}* & \num{-0.73}** & \num{-0.54}*\\
 & (\num{0.22}) & (\num{0.23}) & (\num{0.23}) & (\num{0.25})\\
child.is.girl & \num{1.65}*** & \num{1.72}*** & \num{1.62}*** & \num{1.56}***\\
 & (\num{0.39}) & (\num{0.41}) & (\num{0.39}) & (\num{0.41})\\
child.health & \num{0.28}* & \num{0.29}* & \num{0.19} & \num{0.21}\\
 & (\num{0.13}) & (\num{0.14}) & (\num{0.16}) & (\num{0.15})\\
child.has.rural.hukou & \num{0.47} & \num{0.57} & \num{0.34} & \num{0.47}\\
 & (\num{0.45}) & (\num{0.47}) & (\num{0.43}) & (\num{0.43})\\
child.number.of.sibling & \num{0.29} & \num{0.27} & \num{0.40} & \num{0.21}\\
 & (\num{0.20}) & (\num{0.21}) & (\num{0.23}) & (\num{0.23})\\
child.went.to.preschool & \num{1.05}* & \num{1.26}** & \num{0.65} & \num{1.10}*\\
 & (\num{0.45}) & (\num{0.48}) & (\num{0.42}) & (\num{0.44})\\
child.in.boarding.school & \num{-0.38} & \num{-0.11} & \num{-0.27} & \num{-0.33}\\
 & (\num{0.52}) & (\num{0.49}) & (\num{0.49}) & (\num{0.53})\\
child.education.aspiration & \num{0.61}** & \num{0.70}*** & \num{0.61}** & \num{0.62}**\\
 & (\num{0.18}) & (\num{0.21}) & (\num{0.18}) & (\num{0.21})\\
child.is.ethnic.minority & \num{-0.19} & \num{-0.27} & \num{-0.47} & \num{-0.66}\\
 & (\num{0.67}) & (\num{0.74}) & (\num{0.80}) & (\num{0.85})\\
parent.expectation & \num{0.61}* & \num{0.61}* & \num{0.65}* & \num{0.67}*\\
 & (\num{0.25}) & (\num{0.25}) & (\num{0.29}) & (\num{0.28})\\
parent.has.white.collar.job & \num{-0.18} & \num{-0.06} & \num{-0.08} & \num{0.00}\\
 & (\num{0.27}) & (\num{0.31}) & (\num{0.33}) & (\num{0.34})\\
parent.education.level & \num{0.27} & \num{0.29} & \num{0.33}* & \num{0.33}\\
 & (\num{0.18}) & (\num{0.18}) & (\num{0.17}) & (\num{0.17})\\
home.economic.resource & \num{-0.24} & \num{-0.12} & \num{-0.18} & \num{-0.11}\\
 & (\num{0.27}) & (\num{0.27}) & (\num{0.28}) & (\num{0.27})\\
home.extracurricular.book & \num{-0.26} & \num{-0.41}* & \num{-0.30} & \num{-0.30}*\\
 & (\num{0.17}) & (\num{0.16}) & (\num{0.16}) & (\num{0.15})\\
home.has.internet & \num{-0.41} & \num{-0.48} & \num{-0.32} & \num{-0.39}\\
 & (\num{0.36}) & (\num{0.38}) & (\num{0.40}) & (\num{0.42})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.486} & \num{0.503} & \num{0.490} & \num{0.505}\\
R2 Adj. & \num{0.470} & \num{0.486} & \num{0.473} & \num{0.487}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\end{tabular}
\end{table}

Some predictors are strong in both models of cognitive and academic abilities. These are children's age, preschool attendance, and educational aspiration as well as parents' expectation on children. For students, one year older in age is associated with decreases of 3.43 points for cognitive test and of 0.74 points for academic exam. Preschool attendance is linked to increases of 2.28 points for cognitive test and of 1.05 points for academic exam. Higher educational expectation from parents and greater educational aspiration from children are both linked to higher scores. The coefficients are 0.56 points and 2.42 points for cognitive test, respectively; and 0.27 points and 0.61 points for academic exams, respectively. Some predictors are strong in predicting one outcome but not the other. The covariate that only relates to academic grades is children's gender. Girls outperform boys by 1.65 points in academic exams, but do not show advantage in cognitive tests. Another covariate, the number of siblings, i sonly relate to cognitive scores. Having an additional sibling is associated with lower cognitive score of 0.93 points.

\hypertarget{matching}{%
\subsubsection{Matching}\label{matching}}

Parental migration is not a randomly assigned treatment. Possibly, smart and ambitious students perform better at school, and high performance and ambition prompt parents to migrate to support children's schooling. Another scenario is that poverty may hinder children's educational achievement while driving parents to migrate. The endogeneity leads to selection bias. To tackle this bias, an applicable technique is matching. It aims to make two groups comparable by pairing a unit in the treatment group with one or several units in the control group based on observable covariates.

A popular choice for matching, as Pan and Bai (2018) introduced, is propensity score matching (PSM). For each unit in the sample, PSM will first calculate a propensity score, namely the probability of receiving treatment based on the specified covariates. This score serves as a measure of the distance between two units. When handling this distance, PSM can match the units with two approaches. One is the nearest-neighbor matching. It examines all the treated units and selects the control unit closest in distance for pairing. This approach does not try to optimize any condition; each pair of units ignores how other pairing will occur or have occurred. The second approach is the optimal approach. It minimizes the total distance in propensity scores between the treatment and control groups. Optimal matching can assign a treated unit with more than one control unit, thereby retaining the full sample (Hansen \& Fredrickson, 2023).

Matching with propensity score does not guarantee a more balanced sample. Suppose that in the matching, some covariates are related to the treatment but not to the outcome. In this case, the propensity score estimator's variance would increase. This is like the issue facing linear regression when variables are correlated with the treatment but not with the outcome (Adelson et al., 2017). King and Nielsen (2019) argued against PSM in general as it risks more ``imbalance, model dependence, and bias'' for already balanced data (p.~444). They recommended coarsened exact matching (CEM) as a viable alternative ``for data with continuous, discrete, and mixed variables'' (p.~450). CEM works better in achieving balance as it optimizes the entire joint distribution of covariates. The method's downside is that it leaves many units without a match and discards these unmatched units (Costalli \& Negri, 2021).

I performed matching with all the covariates of the adjusted DID model on the four treatments respectively. My initial attempt with CEM left most units unmatched and resulted in a tiny sample. I then made do with PSM by performing optimal full matching. The propensity score was estimated using a logistic regression of the treatment on all the covariates. According to the matching summary, most of the covariates' absolute standardized mean differences decrease and fall below 0.1 after matching, suggesting an improved overall balance. In the appendix, Figure~\ref{fig:cobal-any} -- Figure~\ref{fig:cobal-both} display the absolute standardized mean differences before and after matching.

The results from models with matching strongly resemble the models without matching, as shown in Table 10 -- Table 13. In the models of cognitive test score, I obtained negative, statistically significant coefficients on all treatment variables except that of both-parents-migrated households. In the models of academic exam score, the treatment variables' coefficients are negative and statistically significant for the any-parent-migrated scenario and the only-mother-migrated scenario. The magnitudes of the statistically significant coefficients are similar to those in the models without matching.

\begin{table}

\caption{Parental migration’s effect on children’s cognitive test score, estimated with matching}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-2.09}** & \num{-2.89}** & \num{-2.60}* & \num{-1.26}\\
 & (\num{0.71}) & (\num{1.07}) & (\num{1.05}) & (\num{1.33})\\
Baseline.score & \num{-0.72}*** & \num{-0.73}*** & \num{-0.71}*** & \num{-0.68}***\\
 & (\num{0.03}) & (\num{0.03}) & (\num{0.03}) & (\num{0.03})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.383} & \num{0.398} & \num{0.408} & \num{0.392}\\
R2 Adj. & \num{0.366} & \num{0.380} & \num{0.390} & \num{0.373}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}Optimal full matching by propensity score}\\
\end{tabular}
\end{table}

\begin{table}

\caption{Parental migration’s effect on children’s cognitive test score, estimated with matching}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-2.10}** & \num{-2.60}* & \num{-2.58}* & \num{-1.59}\\
 & (\num{0.71}) & (\num{1.03}) & (\num{1.07}) & (\num{1.39})\\
Baseline.score & \num{-0.80}*** & \num{-0.80}*** & \num{-0.78}*** & \num{-0.76}***\\
 & (\num{0.03}) & (\num{0.03}) & (\num{0.03}) & (\num{0.03})\\
child.age & \num{-2.54}*** & \num{-2.59}*** & \num{-3.73}*** & \num{-4.20}***\\
 & (\num{0.73}) & (\num{0.69}) & (\num{0.73}) & (\num{0.78})\\
child.is.girl & \num{-1.03} & \num{0.01} & \num{0.15} & \num{-1.12}\\
 & (\num{0.73}) & (\num{0.87}) & (\num{0.71}) & (\num{0.93})\\
child.health & \num{-0.03} & \num{-0.15} & \num{-0.09} & \num{0.46}\\
 & (\num{0.40}) & (\num{0.42}) & (\num{0.44}) & (\num{0.63})\\
child.has.rural.hukou & \num{0.09} & \num{-0.20} & \num{0.66} & \num{0.11}\\
 & (\num{0.94}) & (\num{1.03}) & (\num{1.04}) & (\num{1.16})\\
child.number.of.sibling & \num{-1.22}** & \num{-0.78} & \num{-1.19}* & \num{-0.96}\\
 & (\num{0.43}) & (\num{0.80}) & (\num{0.53}) & (\num{0.70})\\
child.went.to.preschool & \num{2.19}* & \num{1.99}* & \num{2.66}** & \num{-0.13}\\
 & (\num{0.95}) & (\num{0.99}) & (\num{1.00}) & (\num{1.17})\\
child.in.boarding.school & \num{0.54} & \num{0.84} & \num{0.85} & \num{-0.43}\\
 & (\num{1.12}) & (\num{1.61}) & (\num{1.25}) & (\num{1.56})\\
child.education.aspiration & \num{1.91}*** & \num{1.45}** & \num{1.17}*** & \num{1.45}***\\
 & (\num{0.35}) & (\num{0.53}) & (\num{0.34}) & (\num{0.37})\\
child.is.ethnic.minority & \num{2.14} & \num{-0.69} & \num{1.33} & \num{1.84}\\
 & (\num{2.41}) & (\num{2.10}) & (\num{2.27}) & (\num{3.56})\\
parent.expectation & \num{2.62}*** & \num{3.16}*** & \num{2.45}*** & \num{2.13}***\\
 & (\num{0.47}) & (\num{0.59}) & (\num{0.49}) & (\num{0.49})\\
parent.has.white.collar.job & \num{-1.20} & \num{-0.78} & \num{0.08} & \num{-1.90}*\\
 & (\num{0.83}) & (\num{1.02}) & (\num{1.01}) & (\num{0.94})\\
parent.education.level & \num{0.57} & \num{0.76} & \num{-0.23} & \num{0.80}\\
 & (\num{0.39}) & (\num{0.45}) & (\num{0.57}) & (\num{0.63})\\
home.economic.resource & \num{0.18} & \num{-0.66} & \num{0.84} & \num{0.15}\\
 & (\num{0.69}) & (\num{1.01}) & (\num{0.71}) & (\num{0.80})\\
home.extracurricular.book & \num{-0.15} & \num{0.04} & \num{0.54} & \num{0.11}\\
 & (\num{0.35}) & (\num{0.35}) & (\num{0.38}) & (\num{0.40})\\
home.has.internet & \num{-0.01} & \num{-1.96}* & \num{-1.15} & \num{-0.39}\\
 & (\num{0.62}) & (\num{0.87}) & (\num{1.12}) & (\num{0.99})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.432} & \num{0.441} & \num{0.453} & \num{0.440}\\
R2 Adj. & \num{0.415} & \num{0.421} & \num{0.434} & \num{0.420}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}Optimal full matching by propensity score}\\
\end{tabular}
\end{table}

\begin{table}

\caption{Parental migration’s effect on children’s academic exam score, estimated with matching}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-1.09}* & \num{-2.12}* & \num{-0.45} & \num{0.00}\\
 & (\num{0.47}) & (\num{0.87}) & (\num{0.66}) & (\num{0.77})\\
Baseline.score & \num{0.04} & \num{0.05} & \num{0.05} & \num{0.00}\\
 & (\num{0.03}) & (\num{0.03}) & (\num{0.03}) & (\num{0.03})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.480} & \num{0.490} & \num{0.465} & \num{0.515}\\
R2 Adj. & \num{0.465} & \num{0.474} & \num{0.449} & \num{0.500}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}Optimal full matching by propensity score}\\
\end{tabular}
\end{table}

\begin{table}

\caption{Parental migration’s effect on children’s academic exam score, estimated with matching}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Any Parent & Only Mother & Only Father & Both Parents\\
\midrule
Migration & \num{-1.08}* & \num{-2.15}* & \num{-0.42} & \num{0.04}\\
 & (\num{0.45}) & (\num{0.85}) & (\num{0.69}) & (\num{0.78})\\
Baseline.score & \num{0.05}* & \num{-0.01} & \num{-0.01} & \num{-0.04}\\
 & (\num{0.02}) & (\num{0.03}) & (\num{0.04}) & (\num{0.03})\\
child.age & \num{-0.65} & \num{0.07} & \num{-0.74}* & \num{-0.38}\\
 & (\num{0.41}) & (\num{0.45}) & (\num{0.37}) & (\num{0.44})\\
child.is.girl & \num{1.66}*** & \num{1.80}*** & \num{2.18}*** & \num{1.87}***\\
 & (\num{0.44}) & (\num{0.46}) & (\num{0.52}) & (\num{0.50})\\
child.health & \num{0.38}* & \num{0.21} & \num{0.21} & \num{-0.25}\\
 & (\num{0.18}) & (\num{0.17}) & (\num{0.23}) & (\num{0.27})\\
child.has.rural.hukou & \num{0.52} & \num{0.54} & \num{0.95} & \num{0.34}\\
 & (\num{0.50}) & (\num{0.55}) & (\num{0.65}) & (\num{0.70})\\
child.number.of.sibling & \num{0.31} & \num{-0.15} & \num{0.59}* & \num{0.50}\\
 & (\num{0.21}) & (\num{0.41}) & (\num{0.26}) & (\num{0.30})\\
child.went.to.preschool & \num{0.43} & \num{1.18} & \num{0.38} & \num{1.22}\\
 & (\num{0.46}) & (\num{0.61}) & (\num{0.55}) & (\num{0.80})\\
child.in.boarding.school & \num{0.10} & \num{0.27} & \num{-0.33} & \num{-0.70}\\
 & (\num{0.60}) & (\num{0.92}) & (\num{0.84}) & (\num{0.81})\\
child.education.aspiration & \num{0.47}* & \num{0.50} & \num{0.56} & \num{0.38}\\
 & (\num{0.22}) & (\num{0.26}) & (\num{0.32}) & (\num{0.29})\\
child.is.ethnic.minority & \num{-0.31} & \num{-1.04} & \num{-1.40} & \num{-0.51}\\
 & (\num{1.12}) & (\num{1.53}) & (\num{1.20}) & (\num{1.57})\\
parent.expectation & \num{0.48} & \num{1.03}* & \num{0.47} & \num{0.47}\\
 & (\num{0.30}) & (\num{0.43}) & (\num{0.26}) & (\num{0.27})\\
parent.has.white.collar.job & \num{-0.15} & \num{0.13} & \num{0.21} & \num{0.29}\\
 & (\num{0.37}) & (\num{0.49}) & (\num{0.51}) & (\num{0.47})\\
parent.education.level & \num{0.38} & \num{0.23} & \num{0.28} & \num{0.39}\\
 & (\num{0.20}) & (\num{0.23}) & (\num{0.26}) & (\num{0.32})\\
home.economic.resource & \num{0.10} & \num{-0.17} & \num{0.09} & \num{-0.18}\\
 & (\num{0.36}) & (\num{0.41}) & (\num{0.41}) & (\num{0.50})\\
home.extracurricular.book & \num{-0.49}* & \num{-0.35} & \num{-0.15} & \num{-0.27}\\
 & (\num{0.21}) & (\num{0.20}) & (\num{0.25}) & (\num{0.21})\\
home.has.internet & \num{-0.04} & \num{-0.95} & \num{-0.14} & \num{-0.81}\\
 & (\num{0.40}) & (\num{0.51}) & (\num{0.49}) & (\num{0.49})\\
\midrule
Num.Obs. & \num{4204} & \num{3796} & \num{3795} & \num{3671}\\
R2 & \num{0.500} & \num{0.508} & \num{0.485} & \num{0.530}\\
R2 Adj. & \num{0.485} & \num{0.491} & \num{0.467} & \num{0.514}\\
FE: schids & X & X & X & X\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\multicolumn{5}{l}{\rule{0pt}{1em}Optimal full matching by propensity score}\\
\end{tabular}
\end{table}

\hypertarget{discussion-and-conclusion}{%
\subsection{Discussion and Conclusion}\label{discussion-and-conclusion}}

This thesis infers the causal relation between parents' migration and their stay-behind children's educational performance in the short run. Using the 2013-2014 and 2014-2015 rounds of China Education Panel Survey, I build difference-in-differences regression models with fixed-effect and propensity score matching. Results suggest that in the short run, parental migration reduces children's educational performance. This is evidenced by a 1.2 points drop in academic exam grades and a 2.5 points drop in cognitive test scores. This result contrasts with that of DID models by Bai et al. (2018): parental migration is linked to higher English test scores for stay-behind children. The discrepancy could be attributed their study's location, a Northwestern province with grinding poverty. As C. Chen (2023) stated, household economic status conditions the income effect. Only for children in relative impoverishment is a greater amount of remittance associated with better cognitive abilities. This association does not hold for children in better-off households. Another plausibility is that family disruption precedes resource generation. The former's negative effect befalls the left-behind child soon after parental migration, but the latter's positive effect occurs some time later (Wassink \& Viera, 2021). Consequently, I obtain a short-term negative effect.

I further examine whether the effect varies across different arrangements of parental migration. Results indicate that in the short term, children's cognitive ability would decline slightly when one parent migrates and the other one stays. Children's academic performance, however, would decrease mildly only when mother migrates while father stays. This discrepancy is in line with the findings of previous research. China's social norms expect that mothers provide daily care and emotional support to their children. When a mother migrates for work, she defies the cultural expectations on maternal care, thereby harboring bitter and depressive mood in the child's mind. This bitter sentiment can arise even if there is care by father or other relatives (S. Wang, 2023; Xu et al., 2019). Besides, only-mother migration sometimes indicates deeper issues within the household. The father may be unfit for work or engaged in domestic violence, prompting the mother's labor migration (Murphy, 2020). These factors may all hamper children's educational performance. When only father is absent, however, the stay-at-home mother may devote more to the caregiving role. This can partially buffer the impact by her husband's absence and help her child maintain educational performance (Shen et al., 2021).

\hypertarget{limitations}{%
\subsubsection{Limitations}\label{limitations}}

My research has limitations in sampling due to data constraint. Regarding identification, I could only identify parental migration through such a condition: a parent's absence from a household without parental divorce or death. This is because the CEPS questionnaire asked if parents were living in the household, but did not ask why parents were absent. If some parents were jailed or hospitalized, their absence would be wrongly attributed to migration. Besides, I could not control for the migration history of parents, which are not included in the CEPS data. According to Liang and Li (2021), some parents might have out-migrated at an earlier date and returned before the baseline survey. Their children would be attributed to the non-left-behind group. However, these children ``suffer similar disadvantage as that of left behind children'' (p.~12). Liang and Li (2021) argued for a new category: the formerly left-behind children.

Limitations also arise from unaccounted endogeneity and exogeneity. As Chen et al. (2009) discussed in their paper on left-behind children, endogenous factors may create selection bias. When migration opportunities arise, some parents may worry that leaving children behind would hamper children's education, thereby giving up the opportunity. Some other parents may believe that their children's schooling would not suffer from parental absence, thereby embarking on migration. Parental beliefs of this sort are unavailable in CEPS data. Exogenous factors may create omitted variable bias. Suppose that a natural hazard hit many counties of a province in the sample. This shock can increase parents' out-migration and reduce stay-behind students' grades (Chen et al., 2009). I could not account for such shocks as CEPS data does not include detailed geographic information.

\hypertarget{recommendations}{%
\subsubsection{Recommendations}\label{recommendations}}

From my research, we can find new directions for scholarly inquiry. Researchers can explore interaction and moderation in the pathways of resource generation and family disruption. When the CEPS team releases the next round of data, researchers can capitalize a the three-wave panel dataset to build multi-period DID models. This would help examine the parallel trend assumption. Novel methods also offer new possibilities. Machine learning, for example, can estimate the heterogeneous effects across subgroups (R. Liu, 2021). Looking beyond outbound migration, the return migration of parents also worth studying (Liang \& Li, 2021). Not many publications have explored return migrants and their formerly left-behind children in China (see Démurger \& Xu, 2015; Z. Liu et al., 2018).

My research adds to the burgeoning evidence in favor of policy change on the hukou system. China's multilevel citizenship scheme powered by hukou shall not remain as it is, despite the small reduction of newly left-behind children's schooling performance. The slight drop is only the short-term consequence; The lifelong cumulative effect on children may be extensive (Liang \& Sun, 2020; Meng \& Yamauchi, 2017). Besides, educational attainment is only part of human development outcomes. Other outcomes like mental health and non-cognitive skills are also subjected to parental absence's influence (Raturi \& Cebotari, 2023; Zhao \& Chen, 2022).

The children in the CEPS survey have grown into young adults. Would they repeat their parents' choice, leaving the next generation of children behind? That depends on the actions of stakeholders. Policymakers should accelerate the reforms on hukou, opening more doors for parents to migrate together with their children. In January 2023, local government officials lifted hukou restrictions in Zhengzhou, a city that hosts twelve million residents and the world's largest iPhone manufacturing plant (Jiemian News, 2023). This metropolis in central China set the precedant for offering hukou to all arriving migrants; Other main cities should follow suit. Besides top-down policymaking, bottom-up approaches are also necessary. School administrators could dedicate more advisory and counseling programs. Social workers could provide paraprofessional training and community workers can organize children's centers in local areas (Jiang et al., 2020; M. Wang et al., 2020).

\newpage



















\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/v-plot-cog-1} \caption{Changes in cognitive test score for newly left-behind students and non-left-behind students}\label{fig:v-plot-cog}
\end{figure}

\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/v-plot-ttl-1} \caption{Changes in academic exam score for newly left-behind students and non-left-behind students}\label{fig:v-plot-ttl}
\end{figure}

\newpage

\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/cobal-any-1} \caption{Covariate balance before and after matching by any parent migration}\label{fig:cobal-any}
\end{figure}

\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/cobal-mo-1} \caption{Covariate balance before and after matching by mother-only migration}\label{fig:cobal-mo}
\end{figure}

\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/cobal-fa-1} \caption{Covariate balance before and after matching by father-only migration}\label{fig:cobal-fa}
\end{figure}

\begin{figure}
\includegraphics[height=0.4\textheight]{MScThesisText_files/figure-latex/cobal-both-1} \caption{Covariate balance before and after matching by both parents migration}\label{fig:cobal-both}
\end{figure}

\newpage

\hypertarget{references}{%
\section{References}\label{references}}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-adelson2017}{}}%
Adelson, J. L., McCoach, D. B., Rogers, H. J., Adelson, J. A., \& Sauer, T. M. (2017). Developing and applying the propensity score to make causal inferences: Variable selection and stratification. \emph{Frontiers in Psychology}, \emph{8}. \url{https://doi.org/10.3389/fpsyg.2017.01413}

\leavevmode\vadjust pre{\hypertarget{ref-ahmed2023}{}}%
Ahmed, F., Dzator, J., \& Acheampong, A. O. (2023). Do remittances reduce school dropout in bangladesh? The role of government{'}s administrative and structural support. \emph{Journal of Policy Modeling}, \emph{45}(2), 388--404. \url{https://doi.org/10.1016/j.jpolmod.2023.04.002}

\leavevmode\vadjust pre{\hypertarget{ref-R-modelsummary}{}}%
Arel-Bundock, V. (2022). {modelsummary}: Data and model summaries in {R}. \emph{Journal of Statistical Software}, \emph{103}(1), 1--23. \url{https://doi.org/10.18637/jss.v103.i01}

\leavevmode\vadjust pre{\hypertarget{ref-bai2018}{}}%
Bai, Y., Zhang, L., Liu, C., Shi, Y., Mo, D., \& Rozelle, S. (2018). Effect of parental migration on the academic performance of left behind children in north western {China}. \emph{The Journal of Development Studies}, \emph{54}(7), 1154--1170. \url{https://doi.org/10.1080/00220388.2017.1333108}

\leavevmode\vadjust pre{\hypertarget{ref-R-fixest}{}}%
Berge, L., Krantz, S., \& McDermott, G. (2023). \emph{Fixest: Fast fixed-effects estimations}. \url{https://CRAN.R-project.org/package=fixest}

\leavevmode\vadjust pre{\hypertarget{ref-black2021}{}}%
Black, M. M., Behrman, J. R., Daelmans, B., Prado, E. L., Richter, L., Tomlinson, M., Trude, A. C. B., Wertlieb, D., Wuermli, A. J., \& Yoshikawa, H. (2021). The principles of Nurturing Care promote human capital and mitigate adversities from preconception through adolescence. \emph{BMJ Global Health}, \emph{6}(4), e004436. \url{https://doi.org/10.1136/bmjgh-2020-004436}

\leavevmode\vadjust pre{\hypertarget{ref-botezat2020}{}}%
Botezat, A., \& Pfeiffer, F. (2020). The impact of parental labour migration on left{-}behind children's educational and psychosocial outcomes: Evidence from Romania. \emph{Population, Space and Place}, \emph{26}(2). \url{https://doi.org/10.1002/psp.2277}

\leavevmode\vadjust pre{\hypertarget{ref-chae2019}{}}%
Chae, S., \& Glick, J. E. (2019). Educational Selectivity of Migrants and Current School Enrollment of Children Left behind: Analyses in Three African Countries. \emph{International Migration Review}, \emph{53}(3), 736--769. \url{https://doi.org/10.1177/0197918318772261}

\leavevmode\vadjust pre{\hypertarget{ref-chan2019}{}}%
Chan, J. (2019). State and labor in {China}, 1978{\textendash}2018. \emph{Journal of Labor and Society}, \emph{22}(2), 461--475. \url{https://doi.org/10.1111/wusa.12408}

\leavevmode\vadjust pre{\hypertarget{ref-chen2023}{}}%
Chen, C. (2023). Left-Behind Children{'}s Cognitive Development in {China}: Gain in Financial Capital Versus Loss in Parental Capital. \emph{Sociological Perspectives}, \emph{66}(3), 523--542. \url{https://doi.org/10.1177/07311214221145059}

\leavevmode\vadjust pre{\hypertarget{ref-chen2023a}{}}%
Chen, L., Wulczyn, F., \& Huhr, S. (2023). Parental absence, early reading, and human capital formation for rural children in {China}. \emph{Journal of Community Psychology}, \emph{51}(2), 662--675. \url{https://doi.org/10.1002/jcop.22786}

\leavevmode\vadjust pre{\hypertarget{ref-chen2020}{}}%
Chen, T., Kung, J. K., \& Ma, C. (2020). Long Live Keju! The Persistent Effects of {China}{'}s Civil Examination System. \emph{The Economic Journal}, \emph{130}(631), 2030--2064. \url{https://doi.org/10.1093/ej/ueaa043}

\leavevmode\vadjust pre{\hypertarget{ref-chen2023b}{}}%
Chen, X., Allen, J. L., Flouri, E., Cao, X., \& Hesketh, T. (2023). Parent-Child Communication About Educational Aspirations: Experiences of Adolescents in Rural {China}. \emph{Journal of Child and Family Studies}. \url{https://doi.org/10.1007/s10826-023-02554-8}

\leavevmode\vadjust pre{\hypertarget{ref-chen2009}{}}%
Chen, X., Huang, Q., Rozelle, S., Shi, Y., \& Zhang, L. (2009). Effect of Migration on Children's Educational Performance in Rural {China}. \emph{Comparative Economic Studies}, \emph{51}(3), 323--343. \url{https://doi.org/10.1057/ces.2008.44}

\leavevmode\vadjust pre{\hypertarget{ref-chen2019}{}}%
Chen, X., Li, D., Liu, J., Fu, R., \& Liu, S. (2019). Father migration and mother migration: Different implications for social, school, and psychological adjustment of left-behind children in rural {China}. \emph{Journal of Contemporary {China}}, \emph{28}(120), 849--863. \url{https://doi.org/10.1080/10670564.2019.1594100}

\leavevmode\vadjust pre{\hypertarget{ref-chen2023c}{}}%
Chen, Y., \& Fu, W. (2023). Migration control policy and parent{\textendash}child separation among migrant families: evidence from China. \emph{Journal of Population Economics}, In Press. \url{https://doi.org/10.1007/s00148-023-00971-z}

\leavevmode\vadjust pre{\hypertarget{ref-costalli2021}{}}%
Costalli, S., \& Negri, F. (2021). Looking for twins: how to build better counterfactuals with matching. \emph{Italian Political Science Review / Rivista Italiana Di Scienza Politica}, \emph{51}(2), 215--230. \url{https://doi.org/10.1017/ipo.2021.1}

\leavevmode\vadjust pre{\hypertarget{ref-duxe9murger2015}{}}%
Démurger, S., \& Xu, H. (2015). Left-behind children and return migration in {China}. \emph{IZA Journal of Migration}, \emph{4}(1), 10. \url{https://doi.org/10.1186/s40176-015-0035-x}

\leavevmode\vadjust pre{\hypertarget{ref-dewaard2018}{}}%
DeWaard, J., Nobles, J., \& Donato, K. M. (2018). Migration and parental absence: A comparative assessment of transnational families in Latin America. \emph{Population, Space and Place}, \emph{24}(7), e2166. \url{https://doi.org/10.1002/psp.2166}

\leavevmode\vadjust pre{\hypertarget{ref-diaconu-gherasim2023}{}}%
Diaconu-Gherasim, L. R., Brumariu, L. E., \& Etengoff, C. M. (2023). Romanian early adolescents{'} perceptions of parental migration and the associated relational impact: A qualitative analysis. \emph{Journal of Ethnic and Migration Studies}, In Press. \url{https://doi.org/10.1080/1369183X.2023.2203845}

\leavevmode\vadjust pre{\hypertarget{ref-doepke2015}{}}%
Doepke, M. (2015). Gary Becker on the Quantity and Quality of Children. \emph{Journal of Demographic Economics}, \emph{81}(1), 59--66. \url{https://doi.org/10.1017/dem.2014.8}

\leavevmode\vadjust pre{\hypertarget{ref-dong2020}{}}%
Dong, Y., \& Goodburn, C. (2020). Residence Permits and Points Systems: New Forms of Educational and Social Stratification in Urban {China}. \emph{Journal of Contemporary {China}}, \emph{29}(125), 647--666. \url{https://doi.org/10.1080/10670564.2019.1704997}

\leavevmode\vadjust pre{\hypertarget{ref-duckett2020}{}}%
Duckett, J. (2020). Neoliberalism, Authoritarian Politics and Social Policy in {China}. \emph{Development and Change}, \emph{51}(2), 523--539. \url{https://doi.org/10.1111/dech.12568}

\leavevmode\vadjust pre{\hypertarget{ref-fan2023}{}}%
Fan, C. C. (2023). Split households and migration in the {Global South}: Gender and intergenerational perspectives. In B. Yeoh (Ed.), \emph{Handbook on {Migration} and the {Family}} (pp. 135--153). {Edward Elgar Publishing}.

\leavevmode\vadjust pre{\hypertarget{ref-guxf6bel2021}{}}%
Göbel, C. (2021). The political logic of protest repression in {China}. \emph{Journal of Contemporary {China}}, \emph{30}(128), 169--185. \url{https://doi.org/10.1080/10670564.2020.1790897}

\leavevmode\vadjust pre{\hypertarget{ref-gong2023}{}}%
Gong, J., \& Rao, N. (2023). Early learning opportunities of preschool children affected by migration in china. \emph{Early Childhood Research Quarterly}, \emph{63}, 228--239. \url{https://doi.org/10.1016/j.ecresq.2022.12.010}

\leavevmode\vadjust pre{\hypertarget{ref-R-cobalt}{}}%
Greifer, N. (2023). \emph{Cobalt: Covariate balance tables and plots}. \url{https://CRAN.R-project.org/package=cobalt}

\leavevmode\vadjust pre{\hypertarget{ref-gu2022a}{}}%
Gu, X. (2022). Sacrifice and Indebtedness: The Intergenerational Contract in Chinese Rural Migrant Families. \emph{Journal of Family Issues}, \emph{43}(2), 509--533. \url{https://doi.org/10.1177/0192513X21993890}

\leavevmode\vadjust pre{\hypertarget{ref-gu2021a}{}}%
Gu, X., \& Yeung, W. J. (2021). Why do {Chinese} adolescent girls outperform boys in achievement tests? \emph{Chinese Journal of Sociology}, \emph{7}(2), 109--137. \url{https://doi.org/10.1177/2057150X211006586}

\leavevmode\vadjust pre{\hypertarget{ref-guo2021}{}}%
Guo, S., Li, L., Sun, Y., Houang, R., \& Schmidt, W. H. (2021). Does boarding benefit the mathematics achievement of primary and middle school students? Evidence from {China}. \emph{Asia Pacific Journal of Education}, \emph{41}(1), 16--38. \url{https://doi.org/10.1080/02188791.2020.1760081}

\leavevmode\vadjust pre{\hypertarget{ref-hansen2023}{}}%
Hansen, M. M., \& Fredrickson, B. (2023). Optimal full matching. In J. R. Zubizarreta, E. A. Stuart, D. S. Small, \& P. R. Rosenbaum (Eds.), \emph{Handbook of matching and weighting adjustments for causal inference} (pp. 87--104). Chapman; Hall/CRC.

\leavevmode\vadjust pre{\hypertarget{ref-hasmath2023}{}}%
Hasmath, R. (2023). The Operations of Contemporary Han Chinese Privilege. \emph{China Information}, In Press. \url{https://doi.org/10.1177/0920203X231193086}

\leavevmode\vadjust pre{\hypertarget{ref-ho2011}{}}%
Ho, D., Imai, K., King, G., \& Stuart, E. (2011). {MatchIt}: Nonparametric preprocessing for parametric causal inference. \emph{Journal of Statistical Software}, \emph{42}(8), 1--28. \url{https://doi.org/10.18637/jss.v042.i08}

\leavevmode\vadjust pre{\hypertarget{ref-R-MatchIt}{}}%
Ho, D., Imai, K., King, G., Stuart, E., Whitworth, A., \& Greifer, N. (2023). \emph{MatchIt: Nonparametric preprocessing for parametric causal inference}. \url{https://CRAN.R-project.org/package=MatchIt}

\leavevmode\vadjust pre{\hypertarget{ref-huang2020}{}}%
Huang, Y., Liang, Z., Song, Q., \& Tao, R. (2020). Family Arrangements and Children's Education Among Migrants: A Case Study of {China}. \emph{International Journal of Urban and Regional Research}, \emph{44}(3), 484--504. \url{https://doi.org/10.1111/1468-2427.12649}

\leavevmode\vadjust pre{\hypertarget{ref-huntington-klein2022}{}}%
Huntington-Klein, N. (2022). \emph{The Effect: An Introduction to Research Design and Causality}. CRC Press. \url{https://theeffectbook.net/index.html}

\leavevmode\vadjust pre{\hypertarget{ref-R-vtable}{}}%
Huntington-Klein, N. (2023). \emph{Vtable: Variable table for variable documentation}. \url{https://CRAN.R-project.org/package=vtable}

\leavevmode\vadjust pre{\hypertarget{ref-jiang2020}{}}%
Jiang, M., Li, L., Zhu, W. X., \& Hesketh, T. (2020). Community-Based Intervention to Improve the Well-Being of Children Left Behind by Migrant Parents in Rural {China}. \emph{International Journal of Environmental Research and Public Health}, \emph{17}(19), 7218. \url{https://doi.org/10.3390/ijerph17197218}

\leavevmode\vadjust pre{\hypertarget{ref-jiemiannews2023}{}}%
Jiemian News. (2023, January 3). \emph{Zhengzhou relaxes requirements for urban hukou applications {[}in {Chinese}{]}}. \url{https://www.jiemian.com/article/8677930.html}

\leavevmode\vadjust pre{\hypertarget{ref-king2019}{}}%
King, G., \& Nielsen, R. (2019). Why Propensity Scores Should Not Be Used for Matching. \emph{Political Analysis}, \emph{27}(4), 435--454. \url{https://doi.org/10.1017/pan.2019.11}

\leavevmode\vadjust pre{\hypertarget{ref-liang2021}{}}%
Liang, Z., \& Li, W. (2021). Migration and children in {China}: a review and future research agenda. \emph{Chinese Sociological Review}, \emph{53}(3), 312--331. \url{https://doi.org/10.1080/21620555.2021.1908823}

\leavevmode\vadjust pre{\hypertarget{ref-liang2020}{}}%
Liang, Z., \& Sun, F. (2020). The lasting impact of parental migration on children's education and health outcomes: The case of {China}. \emph{Demographic Research}, \emph{S28}(9), 217--244. \url{https://doi.org/10.4054/DemRes.2020.43.9}

\leavevmode\vadjust pre{\hypertarget{ref-liu2020}{}}%
Liu, J., Peng, P., \& Luo, L. (2020). The Relation Between Family Socioeconomic Status and Academic Achievement in {China}: A Meta-analysis. \emph{Educational Psychology Review}, \emph{32}(1), 49--76. \url{https://doi.org/10.1007/s10648-019-09494-0}

\leavevmode\vadjust pre{\hypertarget{ref-liu2020a}{}}%
Liu, M., \& Villa, K. M. (2020). Solution or isolation: Is boarding school a good solution for left-behind children in rural {China}? \emph{{China} Economic Review}, \emph{61}, 101456. \url{https://doi.org/10.1016/j.chieco.2020.101456}

\leavevmode\vadjust pre{\hypertarget{ref-liu2021}{}}%
Liu, R. (2021). Leveraging machine learning methods to estimate heterogeneous effects: Father absence in {China} as an example. \emph{Chinese Sociological Review}, \emph{54}(3), 223--251. \url{https://doi.org/10.1080/21620555.2021.1948828}

\leavevmode\vadjust pre{\hypertarget{ref-liu2023}{}}%
Liu, R., \& Hannum, E. (2023). Parental absence and student academic performance in cross-national perspective: Heterogeneous forms of family separation and the buffering possibilities of grandparents. \emph{International Journal of Educational Development}, \emph{103}, In Press. \url{https://doi.org/10.1016/j.ijedudev.2023.102898}

\leavevmode\vadjust pre{\hypertarget{ref-liu2018}{}}%
Liu, Z., Yu, L., \& Zheng, X. (2018). No longer left-behind: The impact of return migrant parents on children's performance. \emph{{China} Economic Review}, \emph{49}, 184--196. \url{https://doi.org/10.1016/j.chieco.2017.06.004}

\leavevmode\vadjust pre{\hypertarget{ref-luo2013}{}}%
Luo, R., Tamis-LeMonda, C. S., \& Song, L. (2013). Chinese parents{'} goals and practices in early childhood. \emph{Early Childhood Research Quarterly}, \emph{28}(4), 843--857. \url{https://doi.org/10.1016/j.ecresq.2013.08.001}

\leavevmode\vadjust pre{\hypertarget{ref-meng2017}{}}%
Meng, X., \& Yamauchi, C. (2017). Children of migrants: The cumulative impact of parental migration on children{'}s education and health outcomes in {China}. \emph{Demography}, \emph{54}(5), 1677--1714. \url{https://doi.org/10.1007/s13524-017-0613-z}

\leavevmode\vadjust pre{\hypertarget{ref-moeller2015}{}}%
Moeller, J. (2015). A word on standardization in longitudinal studies: don't. \emph{Frontiers in Psychology}, \emph{6}. \url{https://www.frontiersin.org/article/10.3389/fpsyg.2015.01389}

\leavevmode\vadjust pre{\hypertarget{ref-murphy2020}{}}%
Murphy, R. (2020). \emph{The children of {China}{'}s great migration}. Cambridge University Press. \url{https://doi.org/10.1017/9781108877251}

\leavevmode\vadjust pre{\hypertarget{ref-murphy2022}{}}%
Murphy, R. (2022). What does {`}left behind{'} mean to children living in migratory regions in rural {China}? \emph{Geoforum}, \emph{129}, 181--190. \url{https://doi.org/10.1016/j.geoforum.2022.01.012}

\leavevmode\vadjust pre{\hypertarget{ref-nbs2022}{}}%
NBS. (2022). \emph{2021 migrant workers monitor survey report {[}in {Chinese}{]}}. National Bureau of Statistics. \url{http://www.stats.gov.cn/tjsj/zxfb/202204/t20220429_1830126.html}

\leavevmode\vadjust pre{\hypertarget{ref-nbs2017}{}}%
NBS, UNICEF, \& UNFPA. (2017). \emph{Population Status of Children in {China} in 2015: Facts and Figures}. National Bureau of Statistics, United Nations Children's Fund, United Nations Population Fund. \url{https://www.unicef.cn/en/reports/population-status-children-china-2015}

\leavevmode\vadjust pre{\hypertarget{ref-ng2020}{}}%
Ng, F. F.-Y., \& Wei, J. (2020). Delving Into the Minds of Chinese Parents: What Beliefs Motivate Their Learning-Related Practices? \emph{Child Development Perspectives}, \emph{14}(1), 61--67. \url{https://doi.org/10.1111/cdep.12358}

\leavevmode\vadjust pre{\hypertarget{ref-nguyen2016}{}}%
Nguyen, C. V. (2016). Does parental migration really benefit left-behind children? Comparative evidence from Ethiopia, India, Peru and Vietnam. \emph{Social Science \& Medicine}, \emph{153}, 230--239. \url{https://doi.org/10.1016/j.socscimed.2016.02.021}

\leavevmode\vadjust pre{\hypertarget{ref-nsrc}{}}%
NSRC. (n.d.). \emph{Overview-{China} education panel survey}. National Survey Research Center. \url{http://ceps.ruc.edu.cn/English/Overview/Overview.htm}

\leavevmode\vadjust pre{\hypertarget{ref-oecd2016}{}}%
OECD. (2016). \emph{Education in {China}: A snapshot}. \url{https://www.oecd.org/\%7BChina\%7D/Education-in-\%7BChina\%7D-a-snapshot.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-pace2021}{}}%
PACE. (2021). \emph{Resolution 2366: Impact of labour migration on {``}left-behind{''} children}. Parliamentary Assembly of the Council of Europe. \url{https://pace.coe.int/en/files/29077/html}

\leavevmode\vadjust pre{\hypertarget{ref-pan2018}{}}%
Pan, W., \& Bai, H. (2018). Propensity score methods for causal inference: an overview. \emph{Behaviormetrika}, \emph{45}(2), 317--334. \url{https://doi.org/10.1007/s41237-018-0058-8}

\leavevmode\vadjust pre{\hypertarget{ref-pasquali2022}{}}%
Pasquali, P. (2022). Migration regimes and the governance of citizenship: a comparison between legal categories of migration in {China} and in the European Union. \emph{Journal of Chinese Governance}, \emph{7}(4), 633--657. \url{https://doi.org/10.1080/23812346.2020.1791505}

\leavevmode\vadjust pre{\hypertarget{ref-peng2018}{}}%
Peng, Y. (2018). Migrant Mothering in Transition: A Qualitative Study of the Maternal Narratives and Practices of Two Generations of Rural-Urban Migrant Mothers in Southern {China}. \emph{Sex Roles}, \emph{79}(1), 16--35. \url{https://doi.org/10.1007/s11199-017-0855-7}

\leavevmode\vadjust pre{\hypertarget{ref-qian2021}{}}%
Qian, J. (2021). \emph{The Political Economy of Making and Implementing Social Policy in {China}}. Springer Singapore. \url{https://doi.org/10.1007/978-981-16-5025-3}

\leavevmode\vadjust pre{\hypertarget{ref-R-base}{}}%
R Core Team. (2022). \emph{R: A language and environment for statistical computing}. R Foundation for Statistical Computing. \url{https://www.R-project.org/}

\leavevmode\vadjust pre{\hypertarget{ref-raturi2023}{}}%
Raturi, R., \& Cebotari, V. (2023). The impact of parental migration on psychological well-being of children in ghana. \emph{Journal of Ethnic and Migration Studies}, \emph{49}(1), 192--211. \url{https://doi.org/10.1080/1369183X.2022.2076070}

\leavevmode\vadjust pre{\hypertarget{ref-roberts2018}{}}%
Roberts, P., \& Hannum, E. (2018). Education and Equity in Rural {China}: A critical introduction for the rural education field. \emph{Australian and International Journal of Rural Education}, \emph{28}(2). \url{https://doi.org/10.47381/aijre.v28i2.231}

\leavevmode\vadjust pre{\hypertarget{ref-romact2021}{}}%
ROMACT. (2021). \emph{Report on children left behind: Between labour migration, institutional standards, and extended family}. The Council of Europe. \url{https://coe-romact.org/sites/default/files/romact_resources_files/Report_Children\%20Left\%20Behind_ENG_0\%20\%281\%29.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-shen2021}{}}%
Shen, W., Hu, L.-C., \& Hannum, E. (2021). Effect pathways of informal family separation on children's outcomes: Paternal labor migration and long-term educational attainment of left-behind children in rural {China}. \emph{Social Science Research}, \emph{97}, 102576. \url{https://doi.org/10.1016/j.ssresearch.2021.102576}

\leavevmode\vadjust pre{\hypertarget{ref-udrea2022}{}}%
Udrea, G., \& Guiu, G. (2022). The Impact of Parents{'} Work Migration on the Social, Communication and Educational Experiences of Left-Behind Adolescents. \emph{Central and Eastern European Migration Review}, \emph{11}(2), 101--117. \url{https://doi.org/10.54667/ceemr.2022.14}

\leavevmode\vadjust pre{\hypertarget{ref-vanhook2020}{}}%
Van Hook, J., \& Glick, J. E. (2020). Spanning Borders, Cultures, and Generations: A~Decade of Research on Immigrant Families. \emph{Journal of Marriage and Family}, \emph{82}(1), 224--243. \url{https://doi.org/10.1111/jomf.12621}

\leavevmode\vadjust pre{\hypertarget{ref-venta2022}{}}%
Venta, A., \& Cuervo, M. (2022). Attachment, loss, and related challenges in migration. \emph{Current Opinion in Psychology}, \emph{47}, 101406. \url{https://doi.org/10.1016/j.copsyc.2022.101406}

\leavevmode\vadjust pre{\hypertarget{ref-vietnguyen2023}{}}%
Viet Nguyen, C., \& Hoang Vu, L. (2023). Does Parental Absence Harm Children{'}s Education? Evidence from Vietnam. \emph{Journal of Asian and African Studies}, In Press. \url{https://doi.org/10.1177/00219096231176739}

\leavevmode\vadjust pre{\hypertarget{ref-vikram2021}{}}%
Vikram, K. (2021). Fathers{'} Migration and Academic Achievement among Left-behind Children in India: Evidence of Continuity and Change in Gender Preferences. \emph{International Migration Review}, \emph{55}(4), 964--998. \url{https://doi.org/10.1177/0197918321989279}

\leavevmode\vadjust pre{\hypertarget{ref-vortherms2023}{}}%
Vortherms, S. A. (2023). Dividing the {People}: {The Authoritarian Bargain}, {Development}, and {Authoritarian Citizenship}. \emph{Comparative Politics}, \emph{56}(1), 95--119. \url{https://doi.org/10.5129/001041523X16847804956763}

\leavevmode\vadjust pre{\hypertarget{ref-wang2019}{}}%
Wang, L., Zheng, Y., Li, G., Li, Y., Fang, Z., Abbey, C., \& Rozelle, S. (2019). Academic achievement and mental health of left-behind children in rural {China}: A causal study on parental migration. \emph{{China} Agricultural Economic Review}, \emph{11}(4), 569--582. \url{https://doi.org/10.1108/CAER-09-2018-0194}

\leavevmode\vadjust pre{\hypertarget{ref-wang2020a}{}}%
Wang, M., Victor, B. G., Hong, J. S., Wu, S., Huang, J., Luan, H., \& Perron, B. E. (2020). A Scoping Review of Interventions to Promote Health and Well-Being of Left-behind Children in Mainland {China}. \emph{The British Journal of Social Work}, \emph{50}(5), 1419--1439. \url{https://doi.org/10.1093/bjsw/bcz116}

\leavevmode\vadjust pre{\hypertarget{ref-wang2023}{}}%
Wang, S. (2023). Constructing children's psychological well-being: Sources of resilience for children left behind in Northeast {China}. \emph{International Migration}, In Press. \url{https://doi.org/10.1111/imig.13113}

\leavevmode\vadjust pre{\hypertarget{ref-wang2015}{}}%
Wang, W., \& Li, P. (2015). \emph{Psychometric report for the cognitive ability tests of {CEPS} baseline survey (in {Chinese})}. \url{http://ceps.ruc.edu.cn/Enlish/dfiles/11184/14507142239451.pdf}

\leavevmode\vadjust pre{\hypertarget{ref-wassink2021}{}}%
Wassink, J. T., \& Viera, J. A. (2021). Does parental migration during childhood affect children's lifetime educational attainment? Evidence from mexico. \emph{Demography}, \emph{58}(5), 1765--1792. \url{https://doi.org/10.1215/00703370-9411336}

\leavevmode\vadjust pre{\hypertarget{ref-R-tidyverse}{}}%
Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D., François, R., Grolemund, G., Hayes, A., Henry, L., Hester, J., Kuhn, M., Pedersen, T. L., Miller, E., Bache, S. M., Müller, K., Ooms, J., Robinson, D., Seidel, D. P., Spinu, V., \ldots{} Yutani, H. (2019). Welcome to the {tidyverse}. \emph{Journal of Open Source Software}, \emph{4}(43), 1686. \url{https://doi.org/10.21105/joss.01686}

\leavevmode\vadjust pre{\hypertarget{ref-R-haven}{}}%
Wickham, H., Miller, E., \& Smith, D. (2023). \emph{Haven: Import and export {SPSS}, {Stata} and {SAS} files}. \url{https://CRAN.R-project.org/package=haven}

\leavevmode\vadjust pre{\hypertarget{ref-worldbank2020}{}}%
World Bank. (2020). \emph{The human capital index 2020 update}. \url{http://hdl.handle.net/10986/34432}

\leavevmode\vadjust pre{\hypertarget{ref-xu2018}{}}%
Xu, D., Wu, X., Zhang, Z., \& Dronkers, J. (2018). Not a zero-sum game: Migration and child well-being in contemporary {China}. \emph{Demographic Research}, \emph{38}, 691--726. \url{https://doi.org/10.4054/DemRes.2018.38.26}

\leavevmode\vadjust pre{\hypertarget{ref-xu2021}{}}%
Xu, Y., \& Montgomery, C. (2021). Understanding the complexity of Chinese rural parents{'} roles in their children{'}s access to elite universities. \emph{British Journal of Sociology of Education}, \emph{42}(4), 555--570. \url{https://doi.org/10.1080/01425692.2021.1872364}

\leavevmode\vadjust pre{\hypertarget{ref-xu2019}{}}%
Xu, Y., Xu, D., Simpkins, S., \& Warschauer, M. (2019). Does It Matter Which Parent is Absent? Labor Migration, Parenting, and Adolescent Development in {China}. \emph{Journal of Child and Family Studies}, \emph{28}(6), 1635--1649. \url{https://doi.org/10.1007/s10826-019-01382-z}

\leavevmode\vadjust pre{\hypertarget{ref-yang2008}{}}%
Yang, D. (2008). International Migration, Remittances and Household Investment: Evidence from Philippine Migrants{'} Exchange Rate Shocks. \emph{The Economic Journal}, \emph{118}(528), 591--630. \url{https://doi.org/10.1111/j.1468-0297.2008.02134.x}

\leavevmode\vadjust pre{\hypertarget{ref-young2018}{}}%
Young, N. A. E., \& Hannum, E. C. (2018). Childhood Inequality in {China}: Evidence from Recent Survey Data (2012{\textendash}2014). \emph{The {China} Quarterly}, \emph{236}, 1063--1087. \url{https://doi.org/10.1017/S0305741018001303}

\leavevmode\vadjust pre{\hypertarget{ref-zhan2020}{}}%
Zhan, Y. (2020). The moralization of philanthropy in {China}: NGOs, voluntarism, and the reconfiguration of social responsibility. \emph{{China} Information}, \emph{34}(1), 68--87. \url{https://doi.org/10.1177/0920203X19879593}

\leavevmode\vadjust pre{\hypertarget{ref-zhang2018}{}}%
Zhang, C. (2018). Governing neoliberal authoritarian citizenship: Theorizing hukou and the changing mobility regime in {China}. \emph{Citizenship Studies}, \emph{22}(8), 855--881. \url{https://doi.org/10.1080/13621025.2018.1531824}

\leavevmode\vadjust pre{\hypertarget{ref-zhao2022a}{}}%
Zhao, C., \& Chen, B. (2022). Parental migration and non-cognitive abilities of left-behind children in rural china: Causal effects by an instrumental variable approach. \emph{Child Abuse \& Neglect}, \emph{123}, 105389. \url{https://doi.org/10.1016/j.chiabu.2021.105389}

\leavevmode\vadjust pre{\hypertarget{ref-zheng2021}{}}%
Zheng, L., Weng, Q., \& Gong, X. (2021). Does preschool attendance affect the urban-rural cognition gap among middle school students? Evidence from {China Education Panel Survey}. \emph{The Journal of Chinese Sociology}, \emph{8}(1), 14. \url{https://doi.org/10.1186/s40711-021-00150-1}

\leavevmode\vadjust pre{\hypertarget{ref-R-kableExtra}{}}%
Zhu, H. (2021). \emph{kableExtra: Construct complex table with 'kable' and pipe syntax}. \url{https://CRAN.R-project.org/package=kableExtra}

\end{CSLReferences}

\newpage

\hypertarget{appendix-appendix}{%
\appendix}



\end{document}
